
name: Brad's Notebook
description: Make bits and bobs think ğŸ˜€


#url: 
#baseurl: 

avatar: /images/icon.png
favicon: /images/icon.png


navigation:
  - name: Home
    url: /
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags


paginate: 8

# æ–‡ç« ç®€ä»‹çš„åŒºåˆ†æ ‡è®°
excerpt_separator: <!-- more -->

# ä½ çš„ç¤¾äº¤ç½‘ç»œé“¾æ¥ï¼Œå®ƒä»¬ä¼šä½œä¸ºå›¾æ ‡å‡ºç°åœ¨ä½ çš„ç½‘ç«™é¡µè„šä¸­ï¼Œå¯é€‰å¡«å†™
footer-links: 
  weibo: #frommidworld #è¯·è¾“å…¥ä½ çš„å¾®åšä¸ªæ€§åŸŸå https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: brad.821228@gmail.com
  facebook: brad931228 #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: BradXiao #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: bo-wen-xiao-32b52b141 #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #éšä¾¿å¡«ç‚¹å•¥RSSå°±èƒ½ç”¨äº†
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# ç«™ç‚¹é¡µè„šçš„æ–‡å­—
footer-text: Knowledge Is Power

#
# è¯„è®ºï¼Œæ³¨æ„ï¼Œè¯·ä¸è¦åŒæ—¶æ·»åŠ å¤šç§ä¸åŒçš„è¯„è®ºåŒº
#

# è¾“å…¥Disqus shortnameï¼Œå³å¯æ·»åŠ è¯„è®ºåŒº
#disqus: bradxiao #shortname

# è¾“å…¥Gitalkç›¸å…³è®¾å®šï¼Œå³å¯æ·»åŠ è¯„è®ºåŒºï¼Œå…·ä½“è¯·çœ‹æ•™ç¨‹
gitalk:
  clientID: 577a017ec688b4409ae5
  clientSecret: 39f82d743e8d6541202a82c54cf3a10b0233c157
  repo: BradXiao.github.io
  owner: BradXiao

# è¾“å…¥Google Analytics web tracking code
google_analytics:


#
# !! ä»¥ä¸‹æ‰€æœ‰è®¾ç½®éƒ½ä¸éœ€è¦æ›´æ”¹ !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

